### PR TITLE
Fix gradebook update when using editing name shortcut

### PR DESCRIPTION
**Pull request by smuniglia**
Fix proposal for issue : https://github.com/mudrd8mz/moodle-mod_subcourse/issues/30

### CODE REVIEW

**Comment by danmarsden** [comment]
sorry - forgot to point this at the new branch before deleting the old "main" branch - I'll try to remember to come back to this but feel free to push this again under the new MOODLE_401_STABLE branch.

**Comment by ak4t0sh** [comment]
Hi Dan,

AFAIK Sandra is not working on moodle anymore (she was working on it with me @andil-elearning) could you just pick the commit ? 
Otherwise I can pick it on my fork and open a new PR if you prefer.

**Comment by danmarsden** [comment]
@ak4t0sh - can you please provide some more info on what versions you've tested this on and if you have it in production already?

**Comment by danmarsden** [comment]
I've just tested this and cherry-picked it across now - thanks!

**Comment by ak4t0sh** [comment]
Hi Dan sorry for the late answer. Thanks for the cherry-pick !
Yes this patch was tested and deployed on production .

**Pull request closed without merging**
